name: Deploy stage to Cloudflare

on:
    push:
        branches:
            - stage
        paths-ignore:
            - "**/README.md"

jobs:
    deploy-stage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Deploy
              run: |
                  pnpm run stage:deploy-frontend && pnpm run stage:deploy-data-service
              env:
                  # Cloudflare variables
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  VITE_BASE_HOST: ${{ vars.VITE_BASE_HOST_STAGE }}
                  CLOUDFLARE_ENV: stage

            - name: Set runtime environment variables
              run: |
                  cd apps/user-application
                  echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" > .env
                  echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env
                  echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
                  echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
                  npx wrangler secret bulk .env --env stage
              env:
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ENV: stage
